### ISSUE TITLE
Use SetParameters.xml file with Azure Web App Deployment task

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vso-agent-tasks#1106]
I've a WebDeploy package and an accompanying SetParameters.xml file. Is there a way to use the parameters defined in the SetParameters.xml file while running a Azure Web App Deployment task?

**Comment by RoopeshNair** [comment]
In the Additional Arguments of the task, specify the path to the file :

-SetParametersFile $(System.DefaultWorkingDirectory)\<path to the file >\Site.Web.SetParameters.xml

**Comment by pascalberger** [comment]
@RoopeshNair Thanks! I tried this but receive the following error:

    2016-01-22T07:30:09.7262606Z Publish-AzureWebsiteProject -Name "mywebapp" -Package "d:\work\31f6666d3\MySolution.zip" -SetParametersFile d:\work\31f6666d3\MySolution.SetParameters.xml
    2016-01-22T07:30:10.2419369Z ##[error]System.Management.Automation.ParameterBindingException: Cannot bind parameter 'ConnectionString'. Cannot convert the "Manager\Debug\MySolution.SetParameters.xml" value of type "System.String" to type "System.Collections.Hashtable". ---> System.Management.Automation.PSInvalidCastException: Cannot convert the "Manager\Debug\Solutions2Share.Solutions.MeetingManager.Web.SetParameters.xml" value of type "System.String" to type "System.Collections.Hashtable".
    2016-01-22T07:30:10.2419369Z ##[error]   at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
    2016-01-22T07:30:10.2419369Z ##[error]   at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
    2016-01-22T07:30:10.2575083Z ##[error]   at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
    2016-01-22T07:30:10.2575083Z ##[error]   at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
    2016-01-22T07:30:10.2575083Z ##[error]   at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String parameterName, Type toType, ParameterCollectionTypeInformation collectionTypeInfo, Object currentValue)
    2016-01-22T07:30:10.2575083Z ##[error]   --- End of inner exception stack trace ---
    2016-01-22T07:30:10.2575083Z ##[error]   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
    2016-01-22T07:30:10.2575083Z ##[error]   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
    2016-01-22T07:30:10.2575083Z ##[error]   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
    2016-01-22T07:30:10.2575083Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

I don't know which parameter `ConnectionString` it means (I don't have any parameter named like this in my SetParameters file)

**Comment by yaananth** [comment]
That parameter is available for azure powershell v 0.9.5 onwards.
If you are using your agent, ensure it is 0.9.5 + to use this.
Hosted agent is on 0.9.8.1 so it should work there.
