### ISSUE TITLE
NPM v2.3 task seems to have problem with mkdir command

### ISSUE THREAD

**Issue by jochenvanwylick** [Microsoft/vso-agent-tasks#1130]
Hi,

my builds have started failing over night and I think I've tracked it down to the v2.3 version of the NPM task.

Below is a build log of a succesful build that ran last evening:

````
2016-01-25T17:22:24.7062166Z Set workingFolder to default: C:\_Apps\agent_3\tasks\Npm\0.2.0
2016-01-25T17:22:24.7062166Z Prepare node module: vso-task-lib version: Latest Version for task script at workingFolder: C:\_Apps\agent_3\tasks\Npm\0.2.0\node_modules\vso-task-lib.
2016-01-25T17:22:24.7062166Z Reuse junction point from C:\_Apps\agent_3\tasks\Npm\0.2.0\node_modules\vso-task-lib to C:\_Apps\agent_3\modules\vso-task-lib\0.4.5.
2016-01-25T17:22:25.1905453Z ##[debug]check path : C:\Program Files (x86)\nodejs\npm.cmd
2016-01-25T17:22:25.1905453Z ##[debug]npm=C:\Program Files (x86)\nodejs\npm.cmd
2016-01-25T17:22:25.1905453Z ##[debug]command=install
2016-01-25T17:22:25.1905453Z ##[debug]arguments=
2016-01-25T17:22:25.1905453Z ##[debug]cwd=C:\_Apps\agent_3\_work\12\s\Sources\HT Web Platform\Projects\HT.Web.Frontend
2016-01-25T17:22:25.1905453Z [command]C:\Program Files (x86)\nodejs\npm.cmd install
````

Then here's the one from just now. 

````
2016-01-26T11:22:58.0366378Z Set workingFolder to default: C:\_Apps\agent_3\tasks\Npm\0.2.3
2016-01-26T11:22:58.9116465Z ##[debug]check path : C:\_Apps\agent_3\tasks\Npm\0.2.3\task.json
2016-01-26T11:22:58.9116465Z ##[debug]set resource file to: C:\_Apps\agent_3\tasks\Npm\0.2.3\task.json
2016-01-26T11:22:58.9116465Z ##[debug]load loc strings from: C:\_Apps\agent_3\tasks\Npm\0.2.3\task.json
2016-01-26T11:22:58.9116465Z ##[debug]cache loc string: NpmReturnCode
2016-01-26T11:22:58.9116465Z ##[debug]cache loc string: NpmFailed
2016-01-26T11:22:58.9276335Z ##[debug]check path : C:\Program Files (x86)\nodejs\npm.cmd
2016-01-26T11:23:00.6928941Z ##[debug]npm=C:\Program Files (x86)\nodejs\npm.cmd
2016-01-26T11:23:00.7085339Z ##[debug]cwd=C:\_Apps\agent_3\_work\1\s\Sources\HT Web Platform\Projects\HT.Web.Frontend
2016-01-26T11:23:00.7085339Z ##[debug]cwd="C:\_Apps\agent_3\_work\1\s\Sources\HT Web Platform\Projects\HT.Web.Frontend"
2016-01-26T11:23:00.7085339Z ##[debug]creating path: "C:\_Apps\agent_3\_work\1\s\Sources\HT Web Platform\Projects\HT.Web.Frontend"
2016-01-26T11:23:00.7085339Z shell.js: internal error
2016-01-26T11:23:00.7085339Z Error: ENOENT, no such file or directory 'C:\_Apps\agent_3\tasks\Npm\0.2.3\"C:'
2016-01-26T11:23:00.7085339Z     at Error (native)
2016-01-26T11:23:00.7085339Z     at Object.fs.mkdirSync (fs.js:747:18)
2016-01-26T11:23:00.7085339Z     at mkdirSyncRecursive (C:\_Apps\agent_3\tasks\Npm\0.2.3\node_modules\shelljs\src\mkdir.js:11:8)
2016-01-26T11:23:00.7085339Z     at mkdirSyncRecursive (C:\_Apps\agent_3\tasks\Npm\0.2.3\node_modules\shelljs\src\mkdir.js:16:3)
2016-01-26T11:23:00.7085339Z     at mkdirSyncRecursive (C:\_Apps\agent_3\tasks\Npm\0.2.3\node_modules\shelljs\src\mkdir.js:16:3)
2016-01-26T11:23:00.7085339Z     at mkdirSyncRecursive (C:\_Apps\agent_3\tasks\Npm\0.2.3\node_modules\shelljs\src\mkdir.js:16:3)
2016-01-26T11:23:00.7241415Z     at mkdirSyncRecursive (C:\_Apps\agent_3\tasks\Npm\0.2.3\node_modules\shelljs\src\mkdir.js:16:3)
2016-01-26T11:23:00.7241415Z     at mkdirSyncRecursive (C:\_Apps\agent_3\tasks\Npm\0.2.3\node_modules\shelljs\src\mkdir.js:16:3)
2016-01-26T11:23:00.7241415Z     at mkdirSyncRecursive (C:\_Apps\agent_3\tasks\Npm\0.2.3\node_modules\shelljs\src\mkdir.js:16:3)
2016-01-26T11:23:00.7241415Z     at mkdirSyncRecursive (C:\_Apps\agent_3\tasks\Npm\0.2.3\node_modules\shelljs\src\mkdir.js:16:3)
````

As can be observed, the agent is now looking for the NPM task v2.3 and has a problem with the mkdir call.

**Comment by chrisrpatterson** [comment]
We apologize for the issue.  There is a hotfix going out to the service in the next hour that should resolve it.
