### ISSUE TITLE
Azure File Copy never work

### ISSUE THREAD

**Issue by cherici-simone** [Microsoft/vso-agent-tasks#1257]
Hello, I've setup a build and now I'm trying to deploy the artifacts to a blob storage (RM one) but everytime the azure file copy task fail without a significant error message so I don't know what is going on. Here are the last rows from release log:

**2016-02-18T14:41:31.7478720Z ##[error]Upload to container: 'designer' in storage account: 'ssstsmartsuitetest' with blobprefix: '' failed with error: '' For more info please refer to http://aka.ms/azurefilecopyreadme
2016-02-18T14:41:31.7970889Z Finishing task: AzureFileCopy
2016-02-18T14:41:31.7980931Z ##[error]Task AzureFileCopy failed. This caused the job to fail. Look at the logs for the task for more details.**

[Uploading tasklog_4.txt…]()

**Comment by codito** [comment]
We have fixed the task to provide AzCopy.exe error logs.

Please apply this commit 1273c6efc4d1cf46925c271bf983339cf7a8a99b to the local copy of the task? It's in folder `C:\MyAgentDir\tasks\AzureFileCopy`. Also set "System.Debug" to "True" in RM environment variables. This should help get the exact error message.

**Comment by cherici-simone** [comment]
Hi and thank you. I clone the repository and try to build the task but gulp throw an error:


C:\Users\Administrator\Source\Repos\vso-agent-tasks\gulpfile.js:161
    fs.readdirSync(tasksRootFolder).forEach(folderName=> {
                                                       ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\node\node_modu
les\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\node\node_modules\
gulp\node_modules\liftoff\index.js:192:16)
    at module.exports (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\node\node_modules\gulp\
node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
    at Liftoff.<anonymous> (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\node\node_modules\
gulp\node_modules\liftoff\index.js:185:9)

**Comment by cherici-simone** [comment]
Ok, I've upload the new version (and I find out also two more fields for the token key and the blob "path") and the error is that in the argument list I specify /S /Y that are already defined in the task itself.
The error message is:
2016-02-19T10:09:24.7097397Z [2016/02/19 10:09:24][ERROR] The syntax of the command is incorrect. The "S" parameter was specified multiple times.
2016-02-19T10:09:24.7566055Z ##[error]System.Management.Automation.RuntimeException: Upload to container: 'designer' in storage account: 'ssstsmartsuitetest' with blobprefix: '' failed with error: '' For more info please refer to http://aka.ms/azurefilecopyreadme

Note the second row? the description is again null.

By the way thank you, now I have a full build/deploy process.
