### ISSUE TITLE
Nested quote parsing in AppCmd parameter of IISWebAppDeployment

### ISSUE THREAD

**Issue by JamesInDenver** [Microsoft/vso-agent-tasks#1484]
I'm attempting to set the app pool of the released application using the AppCmd function of IISWebAppDeployment:

set app /app.name:"Default Web Site/MyAppName" /applicationPool:AppPoolName

As "Default Web Site" has spaces in it, I need to quote it but nothing I've found will get the properly quoted value all the way through to the AppCmd call.  I've tried a few dozen combinations of single quotes, double quotes, escaped quotes, ticked quotes, etc.  Around both the internal site name and the full command.  

The errors seem to fall into two categories:

The first looks to be failing when parsing the initial task parameters for the IISWebAppDeployment task...
System.Exception: Found value Web with no corresponding named parameter
    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.AddArguments(String argumentString)
 
    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.ScriptExecutor.ExecuteScript(IPowerShell powerShell, String script, String arguments, Boolean isScriptDotSourced, Boolean useHttp)
 
    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.DeploymentService.RunPowerShellScripts(DeploymentMachineSpecification deploymentMachine, ScriptSpecification scriptSpecification, ScriptSpecification initializationScriptSpecification, String applicationPath, IPowerShell powerShellSession)
 
    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.DeploymentService.<RunPowerShellAsync>d__7.MoveNext()

The second looks to be failing when parsing the parameters for the AppCmd call...

Failed to process input: The parameter 'Site/MyAppName\'' must begin with a / or - (HRESULT=80070057)

**Comment by mvvsubbu** [comment]
This one is a known issue, we are planning to bring iis task as extension there we have fixed. For the current version of the task I will port the fix

**Comment by mvvsubbu** [comment]
Fix is in validation phase https://github.com/Microsoft/vso-agent-tasks/issues/1484

**Comment by mvvsubbu** [comment]
Fix committed, it will be deployed in next deployment
