### ISSUE TITLE
NuGet Installer with local nupkg

### ISSUE THREAD

**Issue by FermJacob** [Microsoft/vso-agent-tasks#1504]
When trying to run the NuGet installer build task, I am running into an error listed below.  I am assuming the error for relative URI is for the localRepository, but changing it to `../` does not work either.  Inside of the web portal, I have "Path to Solution", "Path to NuGet.config", and "Disable local cache" filled out and enabled.  Since the "Restore NuGet Packages" is depreciated, I want to implement the new task.  

```
 Set workingFolder to default: B:\tasks\NuGetInstaller\0.1.21
 Executing the powershell script: B:\tasks\NuGetInstaller\0.1.21\NuGetInstaller.ps1
 ##[debug]Loading module from path 'B:\agent\worker\Modules\Microsoft.TeamFoundation.DistributedTask.Task.Internal\Microsoft.TeamFoundation.DistributedTask.Task.Internal.dll'.
 ##[debug]Importing cmdlet 'Add-BuildAttachment'.
 ##[debug]Importing cmdlet 'Convert-String'.
 ##[debug]Importing cmdlet 'Get-IndexedSourceFilePaths'.
 ##[debug]Importing cmdlet 'Get-JavaDevelopmentKitPath'.
 ##[debug]Importing cmdlet 'Get-MSBuildLocation'.
 ##[debug]Importing cmdlet 'Get-ServiceEndpoint'.
 ##[debug]Importing cmdlet 'Get-TfsClientCredentials'.
 ##[debug]Importing cmdlet 'Get-ToolPath'.
 ##[debug]Importing cmdlet 'Get-TaskVariable'.
 ##[debug]Importing cmdlet 'Get-VisualStudioPath'.
 ##[debug]Importing cmdlet 'Get-VssConnection'.
 ##[debug]Importing cmdlet 'Invoke-Ant'.
 ##[debug]Importing cmdlet 'Invoke-BatchScript'.
 ##[debug]Importing cmdlet 'Invoke-Maven'.
 ##[debug]Importing cmdlet 'Invoke-MSBuild'.
 ##[debug]Importing cmdlet 'Invoke-PublishSymbols'.
 ##[debug]Importing cmdlet 'Invoke-Tool'.
 ##[debug]Importing cmdlet 'Invoke-VSTest'.
 ##[debug]Importing cmdlet 'Publish-BuildArtifact'.
 ##[debug]Importing cmdlet 'Copy-BuildArtifact'.
 ##[debug]Importing cmdlet 'Add-BuildArtifactLink'.
 ##[debug]Importing cmdlet 'Register-XamarinLicense'.
 ##[debug]Importing cmdlet 'Unregister-XamarinLicense'.
 ##[debug]Importing cmdlet 'Get-X509Certificate'.
 ##[debug]Loading module from path 'B:\agent\worker\Modules\Microsoft.TeamFoundation.DistributedTask.Task.Common\Microsoft.TeamFoundation.DistributedTask.Task.Common.dll'.
 ##[debug]Importing cmdlet 'Complete-Task'.
 ##[debug]Importing cmdlet 'Get-LocalizedString'.
 ##[debug]Importing cmdlet 'Set-TaskVariable'.
 ##[debug]Importing cmdlet 'Set-TaskProgress'.
 ##[debug]Importing cmdlet 'Add-TaskIssue'.
 ##[debug]Importing cmdlet 'Write-TaskDetail'.
 ##[debug]Importing cmdlet 'Find-Files'.
 ##[debug]Entering script System.Management.Automation.InvocationInfo.MyCommand.Name
 ##[debug]Parameter Values
 ##[debug]solution = B:\Agent\_work\18\s\Automation\SOLUTIONNAME.sln
 ##[debug]nugetConfigPath = B:\Agent\_work\18\s\Automation\PROJECTNAME\nuget.config
 ##[debug]noCache = true
 ##[debug]nuGetRestoreArgs = 
 ##[debug]nuGetPath = 
 ##[debug]No Pattern found in solution parameter.
 ##[debug]Getting credentials for Microsoft.TeamFoundation.DistributedTask.Agent.Common.TaskEndpoint
 ##[debug]Adding credentials section to NuGet.config
 ##[error]System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
 ##[error]   at CallSite.Target(Closure , CallSite , Object , String , String )
 ##[error]   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 ##[error]   at System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
 ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 ##[error]System.Management.Automation.MethodInvocationException: Exception calling "Create" with "1" argument(s): "This operation is not supported for a relative URI." ---> System.InvalidOperationException: This operation is not supported for a relative URI.
 ##[error]   at System.Uri.get_AbsoluteUri()
 ##[error]   at System.Net.WebRequest.Create(Uri requestUri, Boolean useUriBase)
 ##[error]   at CallSite.Target(Closure , CallSite , RuntimeType , Uri )
 ##[error]   --- End of inner exception stack trace ---
 ##[error]   at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
 ##[error]   at CallSite.Target(Closure , CallSite , RuntimeType , Uri )
 ##[error]   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 ##[error]   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 ##[error]System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
 ##[error]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
 ##[error]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
 ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="localRepository" value="..\" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
  <packageRestore>
    <!--Allow NuGet to download missing packages -->
    <add key="enabled" value="True" />
    <!-- Automatically check for missing packages during build in Visual Studio -->
    <add key="automatic" value="True" />
  </packageRestore>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
</configuration>
```

**Comment by vtbassmatt** [comment]
I suspect what's happening is that the build agent doesn't have permission to read directories above your source root (which "..\" is). I'm assuming you have that entry to support dev-box scenarios, and thus cannot take it out?

**Comment by FermJacob** [comment]
I actually did not think about that scenario, but I think your assumption is correct.  I do not have access to the hosted build agent, so I cannot physically put the package on the machine for absolute path.  Is there a solution or a workaround (Other than having a checked-in version different from the local dev box) that could make this work?

And I guess I didn't show the last bit of the log.  It is actually running the install after that message:

```
##[debug]Creating NuGet directory: B:\Agent\_work\18\NuGet\
B:\Agent\_work\18\NuGet
Saving to B:\Agent\_work\18\NuGet\newNuGet.config
##[debug]Running nuget package restore for B:\Agent\_work\18\s\Automation
B:\Agent\agent\worker\tools\NuGet.exe restore "B:\Agent\_work\18\s\Automation\SOLUTIONNAMW.sln"  -NoCache  -NonInteractive -configfile "B:\Agent\_work\18\NuGet\newNuGet.config"
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'. 
Restoring NuGet package Selenium.Support.2.48.2.
Restoring NuGet package Selenium.WebDriver.2.48.2.
Adding package 'Selenium.WebDriver.2.48.2' to folder 'B:\Agent2\_work\16\s\Automation\packages'
Adding package 'Selenium.Support.2.48.2' to folder 'B:\Agent2\_work\16\s\Automation\packages'
```

**Comment by vtbassmatt** [comment]
I'm not 100% sure what you're trying to do. Are you trying to have a persistent local cache of packages? Because if so, the hosted agent won't help you -- the VM gets recycled after each build run.

If you have private or additional packages you want to use with your build, you should use our [package management](https://marketplace.visualstudio.com/items?itemName=ms.feed) features. I'm biased, of course, since that's the part of the product I work on :) There's a decent introduction to the feature [in our documentation](https://www.visualstudio.com/get-started/package/overview).

**Comment by FermJacob** [comment]
I did not know that extension was available. I will look into it!

To your question, No.  Basically, the project was switched over to a VSTS project.  The nupkg was checked in to source control at the .sln level and using the `..\` reference to locate the package when the local 2013 build agent would build the project. When we transferred it over, we used the VS Build task with "Restore NuGet Package" which picked it up just fine because the "Get Sources" would download the file to the Hosted Build Agent.  We used this approach so we could distribute the package without having to create a private NuGet server.

**Comment by FermJacob** [comment]
It is interesting that it still is able to pull down all the packages including the local one after the error occurs.

**Comment by vtbassmatt** [comment]
I think it succeeds because it's still able to pull the packages from nuget.org, it's just failing to find the local copies. If you're OK with it, I recommend removing that internal source from your nuget.config. NuGet on your developer machines will pull from nuget.org the first time, but then after that should retrieve package content from its cache. And then you won't get the errors at build time :)

Of course, I'd be delighted if you install the package management features, but they may not actually be necessary for you.

**Comment by FermJacob** [comment]
It is able to pull the local copy one as well, that is the interesting piece.  I will talk to the admin to get the extension installed.  Thanks for the tip.

**Comment by vtbassmatt** [comment]
:+1:
