### ISSUE TITLE
Agent does not handle "out of disk space" issues safely.

### ISSUE THREAD

**Issue by DaveSullivanAtWork** [Microsoft/vso-agent-tasks#496]
Here is the callstack in the agent window, the agent is now locked, because there is a dialog box open saying the following, which has locked the agent state.  Ideally the agent should handle this and return to a state where it is ready to accept a new job.

**Dialog Displayed**
-------------------------------------------------------------------------------------------------------------------------------------
VsoAgent.exe has stopped working.

A problem caused the program to stop working correctly.  Windows will close the program and notify you if a solution is available

[Debug] [Close Program]

**Callstack of error**
-------------------------------------------------------------------------------------------------------------------------------------
ERROR:
Server stack trace:

ERROR:
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()

ERROR:
   at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)

ERROR:
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)

ERROR:
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)

ERROR:
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

ERROR:
Exception rethrown at [0]:

ERROR:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)

ERROR:
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)

ERROR:
   at Microsoft.TeamFoundation.DistributedTask.Agent.Logger.INetPipeWriter.Disconnect(Guid jobId)

ERROR:
   at Microsoft.TeamFoundation.DistributedTask.Agent.Logger.ForwardingWriter.Dispose()

ERROR:
   at Microsoft.TeamFoundation.DistributedTask.Agent.Worker.Common.BaseLogger.DisposeWriter(String name, ILogWriter writer)

ERROR:
   at Microsoft.TeamFoundation.DistributedTask.Agent.Worker.Common.BaseLogger.Dispose()

ERROR:
   at VsoWorker.Program.Main(String[] args)

ERROR:
There is not enough space on the disk.

WARNING:
Unable to process logging event:##vso[context.logissue type=error;]There is not enough space on the disk.%0D%0A

Unhandled Exception: System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at Microsoft.TeamFoundation.DistributedTask.Agent.Logger.FileWriter.WriteMessage(ILoggerScope scope, String message)
   at Microsoft.TeamFoundation.DistributedTask.Agent.Worker.Common.BaseLogger.LogConsoleMessage(ILoggerScope scope, String message, LoggingVerbosity verbosity)
   at Microsoft.TeamFoundation.DistributedTask.Agent.Worker.Common.BaseContext.LogConsoleMessage(ILoggerScope scope, String message, LoggingVerbosity verbosity)
   at Microsoft.TeamFoundation.DistributedTask.Agent.Worker.Common.BaseContext.LogMessage(Boolean mask, LoggingVerbosity verbosity, String message, Object[] args)
   at Microsoft.TeamFoundation.DistributedTask.Agent.Worker.Common.BaseContext.LogMessage(String message, Object[] args)
   at Microsoft.TeamFoundation.DistributedTask.Agent.WorkerRunner.WorkerProcessExited(Object sender, EventArgs e)
   at Microsoft.TeamFoundation.DistributedTask.Agent.Common.ProcessWrapper.ProcessExitedHandler(Object sender, EventArgs e)
   at Microsoft.TeamFoundation.DistributedTask.Agent.Common.ProcessWrapper.ReadStreamComplete(IAsyncResult result)
   at System.Runtime.Remoting.Messaging.AsyncResult.SyncProcessMessage(IMessage msg)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(IMessage msg, IMessageSink replySink)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by DaveSullivanAtWork** [comment]
Sorry, posted this in the wrong project.
