### ISSUE TITLE
Not able to upload agent tasks to TFS 2015

### ISSUE THREAD

**Issue by codelabexpert** [Microsoft/vso-agent-tasks#593]
Hello,
I am not able to upload the tasks to TFS 2015.
 - fresh npm Installation
 - fresh tfx-cli Installation

I get this error message:

E:\dev\Tfs\Tasks\vso-agent-tasks\Tasks>tfx login --authType basic
Copyright Microsoft Corporation

Enter collection url > http://tfs-01:8080/tfs
http://tfs-01:8080/tfs
Enter username > mydomain\qml
Enter password >
logged in successfully

E:\dev\Tfs\Tasks\vso-agent-tasks\Tasks>SET TFX_TRACE=1

E:\dev\Tfs\Tasks\vso-agent-tasks\Tasks>tfx build tasks upload DeployVisualStudioTestAgent
2015-09-24T11:10:14.399Z : loader.load
2015-09-24T11:10:14.403Z : build-list.js
2015-09-24T11:10:14.404Z : build-queue.js
2015-09-24T11:10:14.404Z : build-show.js
2015-09-24T11:10:14.404Z : build-tasks-create.js
2015-09-24T11:10:14.405Z : build-tasks-delete.js
2015-09-24T11:10:14.405Z : build-tasks-list.js
2015-09-24T11:10:14.405Z : build-tasks-upload.js
2015-09-24T11:10:14.406Z : build-tasks.js
2015-09-24T11:10:14.406Z : build.js
2015-09-24T11:10:14.406Z : help.js
2015-09-24T11:10:14.407Z : login.js
2015-09-24T11:10:14.407Z : parse.js
2015-09-24T11:10:14.407Z : resources
2015-09-24T11:10:14.408Z : version.js
2015-09-24T11:10:14.408Z : loader.match
2015-09-24T11:10:14.409Z : Command matched
2015-09-24T11:10:14.409Z : No command matched
2015-09-24T11:10:14.590Z : loaded C:\Users\qml\AppData\Roaming\npm\node_modules\tfx-cli\exec\build-tasks-upload.js
Copyright Microsoft Corporation

2015-09-24T11:10:14.591Z : loader.getCollectionUrl
2015-09-24T11:10:14.592Z : loader.getCachedUrl
2015-09-24T11:10:14.617Z : Retrieved collection url from cache
2015-09-24T11:10:14.618Z : url: http://tfs-01:8080/tfs
2015-09-24T11:10:14.619Z : inputs.check
2015-09-24T11:10:14.620Z : auth.getCredentials
2015-09-24T11:10:14.621Z : auth.getCachedCredentials
2015-09-24T11:10:14.624Z : Retrieved credentials from cache
2015-09-24T11:10:14.625Z : Using basic creds
2015-09-24T11:10:14.628Z : build-task-upload.exec
2015-09-24T11:10:14.629Z : tfcommand.checkArguments
2015-09-24T11:10:14.629Z : inputs.check
2015-09-24T11:10:14.630Z : taskPath: DeployVisualStudioTestAgent
2015-09-24T11:10:14.631Z : task.json path: E:\dev\Tfs\Tasks\vso-agent-tasks\Tasks\DeployVisualStudioTestAgent\task.json
2015-09-24T11:10:14.631Z : Validating task json...
2015-09-24T11:10:14.634Z : Json is valid.
2015-09-24T11:10:14.640Z : Initializing agent API...
unhandled:
TypeError: Cannot read property 'value' of null
    at C:\Users\qml\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\VsoClient.js:101:60
    at processResponse (C:\Users\qml\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\RestClient.js:56:9)
    at C:\Users\qml\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\RestClient.js:164:13
    at IncomingMessage.<anonymous> (C:\Users\qml\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\HttpClient.js:120:17)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

E:\dev\Tfs\Tasks\vso-agent-tasks\Tasks>

What should I do? Thank you!

**Comment by stevetsang** [comment]
I experience the same issue (https://github.com/Microsoft/tfs-cli/issues/46). Hopefully the link will help you with your problem.

**Comment by ericsciple** [comment]
@codelabexpert as Steve pointed out, you entered the server URL instead of the collection URL. The error message is terrible, I opened an issue on the tfx-cli here: https://github.com/Microsoft/tfs-cli/issues/50

Closing the issue here.
