### ISSUE TITLE
Cleaning repository fails on build agent

### ISSUE THREAD

**Issue by tghamm** [Microsoft/vso-agent-tasks#842]
I've got clean repository enabled and it fails, forcing me to manually remove the files from our build server.  

If helpful, it's trying to remove a bunch of node modules that almost certainly exceed the file path limit.  It's also a LOT of files, ~20k or more.

Anything we can do to fix that?

    Starting: Get sources
    ******************************************************************************
    System.ComponentModel.Win32Exception (0x80004005): The system cannot find the path specified
    at Microsoft.TeamFoundation.Common.FileSpec.DeleteDirectoryLongPath(String path, Boolean recursive)
    at Microsoft.TeamFoundation.Common.FileSpec.DeleteDirectoryLongPath(String path, Boolean recursive)
    at Microsoft.TeamFoundation.Common.FileSpec.DeleteDirectoryLongPath(String path, Boolean recursive)
    at Microsoft.TeamFoundation.Common.FileSpec.DeleteDirectoryLongPath(String path, Boolean recursive)
    at Microsoft.TeamFoundation.Common.FileSpec.DeleteDirectoryLongPath(String path, Boolean recursive)
    at Microsoft.TeamFoundation.Common.FileSpec.DeleteDirectoryLongPath(String path, Boolean recursive)
    at Microsoft.TeamFoundation.Common.FileSpec.DeleteDirectoryLongPath(String path, Boolean recursive)
    at Microsoft.TeamFoundation.Common.FileSpec.DeleteDirectoryLongPath(String path, Boolean recursive)
    at Microsoft.TeamFoundation.Common.FileSpec.DeleteDirectoryLongPath(String path, Boolean recursive)
    at Microsoft.TeamFoundation.DistributedTask.Agent.Common.PathHelper.TryDeleteDirectory(String path, Boolean recursive, Boolean throwOnFailure)
    at Microsoft.TeamFoundation.DistributedTask.Plugin.Build.SourceProviderManager.GetSources(CancellationToken cancellationToken)
    at Microsoft.TeamFoundation.DistributedTask.Plugin.Build.BuildJobExtension.OnPrepareEnvironment(IJobContext context, IDictionary`2 savedSettings, IJobRequest job, CancellationToken cancellationToken)
    at Microsoft.TeamFoundation.DistributedTask.Worker.JobExtensionManager.<>c__DisplayClass8.<OnPrepareEnvironment>b__7()
    at Microsoft.TeamFoundation.DistributedTask.Worker.JobExtensionManager.TryAction(String method, Action action, Boolean throwOnError)
    at Microsoft.TeamFoundation.DistributedTask.Worker.JobExtensionManager.OnPrepareEnvironment(IJobContext context, IDictionary`2 savedSettings, IJobRequest job, CancellationToken cancellationToken)
    at Microsoft.TeamFoundation.DistributedTask.Worker.Worker.Run()

**Comment by bryanmacfarlane** [comment]
This repo is for the build tasks and that issue is for the .net win agent (not in this repo).  I will close, however I will send to a dev for comment.

**Comment by bryanmacfarlane** [comment]
Ting - please comment.
