### ISSUE TITLE
npm install doesn't work with python libraries

### ISSUE THREAD

**Issue by rosieks** [Microsoft/vso-agent-tasks#943]
I tried to build application created with this yeoman generator: https://github.com/Swiip/generator-gulp-angular

Unfortunately it fails to build on VSTS, probably because some libraries that use python. Below few errors:

	2015-12-07T20:08:42.4949771Z C:\a\1\s\node_modules\webpack-stream\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\fsevents>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\a\1\s\node_modules\webpack-stream\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\fsevents\lib\binding\Release\node-v14-win32-x64\fse.node --module_name=fse --module_path=C:\a\1\s\node_modules\webpack-stream\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\fsevents\lib\binding\Release\node-v14-win32-x64 )  else (node  configure --fallback-to-build --module=C:\a\1\s\node_modules\webpack-stream\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\fsevents\lib\binding\Release\node-v14-win32-x64\fse.node --module_name=fse --module_path=C:\a\1\s\node_modules\webpack-stream\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\fsevents\lib\binding\Release\node-v14-win32-x64 ) 
	2015-12-07T20:08:43.7449769Z ##[error]Traceback (most recent call last):
	2015-12-07T20:08:43.7606015Z ##[error]  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 18, in <module>
	2015-12-07T20:08:43.8231034Z ##[error]    sys.exit(gyp.script_main())
	2015-12-07T20:08:43.8231034Z ##[error]  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 533, in script_main
	2015-12-07T20:08:43.8387282Z ##[error]    return main(sys.argv[1:])
	2015-12-07T20:08:43.8387282Z ##[error]  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 526, in main
	2015-12-07T20:08:43.9949771Z ##[error]    return gyp_main(args)
	2015-12-07T20:08:43.9949771Z ##[error]  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 511, in gyp_main
	2015-12-07T20:08:43.9949771Z ##[error]    generator.GenerateOutput(flat_list, targets, data, params)
	2015-12-07T20:08:43.9949771Z ##[error]  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2000, in GenerateOutput
	2015-12-07T20:08:43.9949771Z ##[error]    sln_projects, project_objects, flat=msvs_version.FlatSolution())
	2015-12-07T20:08:43.9949771Z ##[error]  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1759, in _GatherSolutionFolders
	2015-12-07T20:08:43.9949771Z ##[error]    return _DictsToFolders('', root, flat)
	2015-12-07T20:08:43.9949771Z ##[error]  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1712, in _DictsToFolders
	2015-12-07T20:08:43.9949771Z ##[error]    for folder, contents in bucket.iteritems():
	2015-12-07T20:08:43.9949771Z ##[error]AttributeError: 'MSVSProject' object has no attribute 'iteritems'
	2015-12-07T20:08:43.9949771Z ##[error]gyp ERR! configure error 
	2015-12-07T20:08:43.9949771Z ##[error]gyp ERR! stack Error: `gyp` failed with exit code: 1
	2015-12-07T20:08:43.9949771Z ##[error]gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:355:16)
	2015-12-07T20:08:43.9949771Z ##[error]gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
	2015-12-07T20:08:44.2137297Z ##[error]gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
	2015-12-07T20:08:44.2293540Z ##[error]gyp ERR! System Windows_NT 6.3.9600
	2015-12-07T20:08:44.6200062Z ##[error]gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\a\\1\\s\\node_modules\\webpack-stream\\node_modules\\webpack\\node_modules\\watchpack\\node_modules\\chokidar\\node_modules\\fsevents\\lib\\binding\\Release\\node-v14-win32-x64\\fse.node" "--module_name=fse" "--module_path=C:\\a\\1\\s\\node_modules\\webpack-stream\\node_modules\\webpack\\node_modules\\watchpack\\node_modules\\chokidar\\node_modules\\fsevents\\lib\\binding\\Release\\node-v14-win32-x64"
	2015-12-07T20:08:44.6200062Z ##[error]gyp ERR! cwd C:\a\1\s\node_modules\webpack-stream\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\fsevents
	2015-12-07T20:08:44.6200062Z ##[error]gyp ERR! node -v v0.12.7
	2015-12-07T20:08:44.6200062Z ##[error]gyp ERR! node-gyp -v v2.0.1
	2015-12-07T20:08:44.6200062Z ##[error]gyp ERR! not ok 
	2015-12-07T20:08:44.6200062Z ##[error]node-pre-gyp ERR! build error 
	2015-12-07T20:08:44.6200062Z ##[error]node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\a\1\s\node_modules\webpack-stream\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\fsevents\lib\binding\Release\node-v14-win32-x64\fse.node --module_name=fse --module_path=C:\a\1\s\node_modules\webpack-stream\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\fsevents\lib\binding\Release\node-v14-win32-x64' (1)
	2015-12-07T20:08:44.6200062Z ##[error]node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\a\1\s\node_modules\webpack-stream\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\fsevents\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
	2015-12-07T20:08:44.6356035Z ##[error]node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
	2015-12-07T20:08:44.6356035Z ##[error]node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
	2015-12-07T20:08:44.6356035Z ##[error]node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
	2015-12-07T20:08:44.6356035Z ##[error]node-pre-gyp ERR! System Windows_NT 6.3.9600
	2015-12-07T20:08:44.6356035Z ##[error]node-pre-gyp ERR! command "node" "C:\\a\\1\\s\\node_modules\\webpack-stream\\node_modules\\webpack\\node_modules\\watchpack\\node_modules\\chokidar\\node_modules\\fsevents\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
	2015-12-07T20:08:44.6356035Z ##[error]node-pre-gyp ERR! cwd C:\a\1\s\node_modules\webpack-stream\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\fsevents
	2015-12-07T20:08:44.6356035Z ##[error]node-pre-gyp ERR! node -v v0.12.7
	2015-12-07T20:08:44.6356035Z ##[error]node-pre-gyp ERR! node-pre-gyp -v v0.6.15
	2015-12-07T20:08:44.6356035Z ##[error]node-pre-gyp ERR! not ok 

	2015-12-07T20:08:45.3231018Z C:\a\1\s\node_modules\karma\node_modules\chokidar\node_modules\fsevents>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\a\1\s\node_modules\karma\node_modules\chokidar\node_modules\fsevents\lib\binding\Release\node-v14-win32-x64\fse.node --module_name=fse --module_path=C:\a\1\s\node_modules\karma\node_modules\chokidar\node_modules\fsevents\lib\binding\Release\node-v14-win32-x64 )  else (node  configure --fallback-to-build --module=C:\a\1\s\node_modules\karma\node_modules\chokidar\node_modules\fsevents\lib\binding\Release\node-v14-win32-x64\fse.node --module_name=fse --module_path=C:\a\1\s\node_modules\karma\node_modules\chokidar\node_modules\fsevents\lib\binding\Release\node-v14-win32-x64 ) 
	2015-12-07T20:08:46.4168531Z ##[error]Traceback (most recent call last):
	2015-12-07T20:08:46.4168531Z ##[error]  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 18, in <module>
	2015-12-07T20:08:46.4324769Z ##[error]    sys.exit(gyp.script_main())
	2015-12-07T20:08:46.4324769Z ##[error]  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 533, in script_main
	2015-12-07T20:08:46.4324769Z ##[error]    return main(sys.argv[1:])
	2015-12-07T20:08:46.4324769Z ##[error]  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 526, in main
	2015-12-07T20:08:46.4324769Z ##[error]    return gyp_main(args)
	2015-12-07T20:08:46.4324769Z ##[error]  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 511, in gyp_main
	2015-12-07T20:08:46.4324769Z ##[error]    generator.GenerateOutput(flat_list, targets, data, params)
	2015-12-07T20:08:46.4324769Z ##[error]  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2000, in GenerateOutput
	2015-12-07T20:08:46.4324769Z ##[error]    sln_projects, project_objects, flat=msvs_version.FlatSolution())
	2015-12-07T20:08:46.4324769Z ##[error]  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1759, in _GatherSolutionFolders
	2015-12-07T20:08:46.4324769Z ##[error]    return _DictsToFolders('', root, flat)
	2015-12-07T20:08:46.4324769Z ##[error]  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1712, in _DictsToFolders
	2015-12-07T20:08:46.4481024Z ##[error]    for folder, contents in bucket.iteritems():
	2015-12-07T20:08:46.4481024Z ##[error]AttributeError: 'MSVSProject' object has no attribute 'iteritems'
	2015-12-07T20:08:46.4481024Z ##[error]gyp ERR! configure error 
	2015-12-07T20:08:46.4481024Z ##[error]gyp ERR! stack Error: `gyp` failed with exit code: 1
	2015-12-07T20:08:46.4481024Z ##[error]gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:355:16)
	2015-12-07T20:08:46.4481024Z ##[error]gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
	2015-12-07T20:08:46.4481024Z ##[error]gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
	2015-12-07T20:08:46.4481024Z ##[error]gyp ERR! System Windows_NT 6.3.9600
	2015-12-07T20:08:46.4481024Z ##[error]gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\a\\1\\s\\node_modules\\karma\\node_modules\\chokidar\\node_modules\\fsevents\\lib\\binding\\Release\\node-v14-win32-x64\\fse.node" "--module_name=fse" "--module_path=C:\\a\\1\\s\\node_modules\\karma\\node_modules\\chokidar\\node_modules\\fsevents\\lib\\binding\\Release\\node-v14-win32-x64"
	2015-12-07T20:08:46.4481024Z ##[error]gyp ERR! cwd C:\a\1\s\node_modules\karma\node_modules\chokidar\node_modules\fsevents
	2015-12-07T20:08:46.4481024Z ##[error]gyp ERR! node -v v0.12.7
	2015-12-07T20:08:46.4481024Z ##[error]gyp ERR! node-gyp -v v2.0.1
	2015-12-07T20:08:46.4481024Z ##[error]gyp ERR! not ok 
	2015-12-07T20:08:46.4637281Z ##[error]node-pre-gyp ERR! build error 
	2015-12-07T20:08:46.4794871Z ##[error]node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\a\1\s\node_modules\karma\node_modules\chokidar\node_modules\fsevents\lib\binding\Release\node-v14-win32-x64\fse.node --module_name=fse --module_path=C:\a\1\s\node_modules\karma\node_modules\chokidar\node_modules\fsevents\lib\binding\Release\node-v14-win32-x64' (1)
	2015-12-07T20:08:46.4794871Z ##[error]node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\a\1\s\node_modules\karma\node_modules\chokidar\node_modules\fsevents\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
	2015-12-07T20:08:46.4794871Z ##[error]node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
	2015-12-07T20:08:46.4794871Z ##[error]node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
	2015-12-07T20:08:46.4794871Z ##[error]node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
	2015-12-07T20:08:46.4794871Z ##[error]node-pre-gyp ERR! System Windows_NT 6.3.9600
	2015-12-07T20:08:46.4794871Z ##[error]node-pre-gyp ERR! command "node" "C:\\a\\1\\s\\node_modules\\karma\\node_modules\\chokidar\\node_modules\\fsevents\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
	2015-12-07T20:08:46.4794871Z ##[error]node-pre-gyp ERR! cwd C:\a\1\s\node_modules\karma\node_modules\chokidar\node_modules\fsevents
	2015-12-07T20:08:46.4794871Z ##[error]node-pre-gyp ERR! node -v v0.12.7
	2015-12-07T20:08:46.4794871Z ##[error]node-pre-gyp ERR! node-pre-gyp -v v0.6.15
	2015-12-07T20:08:46.4794871Z ##[error]node-pre-gyp ERR! not ok 

	2015-12-07T20:08:54.1985414Z C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(214): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc [C:\a\1\s\node_modules\gulp-protractor\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
	2015-12-07T20:08:54.4641663Z      Creating library C:\a\1\s\node_modules\gulp-protractor\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil\build\Release\bufferutil.lib and object C:\a\1\s\node_modules\gulp-protractor\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil\build\Release\bufferutil.exp
	2015-12-07T20:08:54.6047895Z   Generating code
	2015-12-07T20:08:55.1360411Z   Finished generating code
	2015-12-07T20:08:55.7141678Z   bufferutil.vcxproj -> C:\a\1\s\node_modules\gulp-protractor\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil\build\Release\\bufferutil.node
	2015-12-07T20:08:55.9954220Z ##[error]npm ERR! Windows_NT 6.3.9600
	2015-12-07T20:08:55.9954220Z ##[error]npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--force"
	2015-12-07T20:08:56.0124866Z ##[error]npm ERR! node v0.12.7
	2015-12-07T20:08:56.0124866Z ##[error]npm ERR! npm  v2.11.3
	2015-12-07T20:08:56.0124866Z ##[error]npm ERR! shasum check failed for C:\Users\BUILDG~1\AppData\Local\Temp\npm-1868-a00249dc\registry.npmjs.org\browser-sync-ui\-\browser-sync-ui-0.5.16.tgz
	2015-12-07T20:08:56.0124866Z ##[error]npm ERR! Expected: e08b5fb1d5c7587e996f815c4c5e7e4c2532f2e8
	2015-12-07T20:08:56.0422938Z ##[error]npm ERR! Actual:   7d900fb875d2dace6b60956da695f3a3349cebb0
	2015-12-07T20:08:56.1047919Z ##[error]npm ERR! From:     https://registry.npmjs.org/browser-sync-ui/-/browser-sync-ui-0.5.16.tgz
	2015-12-07T20:08:56.2922905Z ##[error]npm ERR! 
	2015-12-07T20:08:56.3079161Z ##[error]npm ERR! If you need help, you may report this error at:
	2015-12-07T20:08:56.3079161Z ##[error]npm ERR!     <https://github.com/npm/npm/issues>
	2015-12-07T20:08:56.3079161Z ##[error]npm ERR! Please include the following file with any support request:
	2015-12-07T20:08:56.3079161Z ##[error]npm ERR!     C:\a\1\s\npm-debug.log
	2015-12-07T20:08:56.3235408Z ##[error]Unexpected exit code 1 returned from tool npm.cmd

**Comment by bryanmacfarlane** [comment]
If npm install has a gyp that calls other toolsets and dependencies (not just pulling a node module), then it is possible on VSO.  But you will have to bring your own VM ( http://aka.ms/tfbuild ) with the tools you need to install.

If you're convinced it's just python then we could discuss adding that to our hosted image (but realize the hosted build agent is a static set of tools)

**Comment by rosieks** [comment]
I'm not 100% sure if this is just python. I'm still don't understand what happens in this all node/gulp tasks. What I now is that in all that errors are used quite common tools like karma, protractor or webpack. And because they are quite popular the should work out of the box on hosted image.

**Comment by bryanmacfarlane** [comment]
We will add it to the backlog for the hosted image.  In the mean time, agent VM is the workaround.

**Comment by bryanmacfarlane** [comment]
closing and moving to the hosted image backlog

**Comment by rosieks** [comment]
Is there any image in Azure Marketplace that I can use to have ready to use VM?

**Comment by rosieks** [comment]
@bryanmacfarlane 
It looks like it's not related to lacking of python on build serve, but rather error in NPM. It looks like it was fixed in NPM 3.2.0 and then introduced again in NPM 3.5.0
https://github.com/npm/npm/issues/8921

Maybe in such case it would be nice if there would be option to select NPM version in NPM task. Something similar to what we have MSBuild task (MSBuild version field)
